#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import { copyFile, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = resolveSourceRoot(process.argv.slice(2));
const schemaSource = join(sourceRoot, "codex-rs/core/config.schema.json");
const modelsSource = join(sourceRoot, "codex-rs/models-manager/models.json");
const featuresSource = join(sourceRoot, "codex-rs/features/src/lib.rs");
const legacyFeaturesSource = join(sourceRoot, "codex-rs/features/src/legacy.rs");
const sourceInputPaths = [
  "codex-rs/core/config.schema.json",
  "codex-rs/models-manager/models.json",
  "codex-rs/features/src/lib.rs",
  "codex-rs/features/src/legacy.rs",
];
if (gitOutput(sourceRoot, ["rev-parse", "--is-shallow-repository"]) === "true") {
  throw new Error("A full Codex git checkout is required to recover retired feature keys.");
}
const modifiedSourceInputs = gitOutput(sourceRoot, [
  "diff",
  "--name-only",
  "HEAD",
  "--",
  ...sourceInputPaths,
]);
if (modifiedSourceInputs) {
  throw new Error(
    `Refusing to label modified Codex source inputs as HEAD:\n${modifiedSourceInputs}`,
  );
}

const [modelsJson, featuresRust, legacyFeaturesRust] = await Promise.all([
  readFile(modelsSource, "utf8").then(JSON.parse),
  readFile(featuresSource, "utf8"),
  readFile(legacyFeaturesSource, "utf8"),
]);

const expectedModelIds = ["gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna"];
const models = modelsJson.models
  .filter((model) => /^gpt-5\.6-(sol|terra|luna)$/.test(model.slug))
  .map((model) => ({
    id: model.slug,
    displayName: model.display_name,
    contextWindow: model.context_window,
    reasoningEfforts: model.supported_reasoning_levels.map((entry) => entry.effort),
    defaultReasoningEffort: model.default_reasoning_level,
    defaultReasoningSummary: model.default_reasoning_summary,
    supportsVerbosity: model.support_verbosity,
    serviceTiers: model.service_tiers.map((entry) => entry.id),
    minimumClientVersion: model.minimal_client_version,
    toolMode: model.tool_mode,
    multiAgentVersion: model.multi_agent_version,
    supportsPersonality: supportsPersonality(model.model_messages),
  }))
  .sort((left, right) => expectedModelIds.indexOf(left.id) - expectedModelIds.indexOf(right.id));

const defaultModel = "gpt-5.6-sol";
if (JSON.stringify(models.map((model) => model.id)) !== JSON.stringify(expectedModelIds)) {
  throw new Error(`Expected the complete GPT-5.6 model family in ${modelsSource}`);
}

const minimumClientVersion = maxVersion(models.map((model) => model.minimumClientVersion));

const featureCatalog = parseFeatureCatalog(featuresRust);
const legacyFeatureAliases = parseLegacyFeatureAliases(legacyFeaturesRust, featureCatalog);
const currentFeatureKeys = new Set(parseFeatureKeys(featuresRust));
const currentLegacyFeatureKeys = new Set(Object.keys(legacyFeatureAliases));
const retiredFeatureKeys = parseHistoricalFeatureKeys(
  gitOutput(sourceRoot, [
    "log",
    "--first-parent",
    "--follow",
    "-p",
    "--format=",
    "--",
    "codex-rs/features/src/lib.rs",
  ]),
).filter(
  (key) => !currentFeatureKeys.has(key) && !currentLegacyFeatureKeys.has(key),
);
const target = {
  sourceRevision: gitOutput(sourceRoot, ["rev-parse", "HEAD"]),
  sourceCommitDate: gitOutput(sourceRoot, ["show", "-s", "--format=%cI", "HEAD"]),
  minimumClientVersion,
  defaultModel,
  models,
  removedFeatureKeys: featureCatalog
    .filter((feature) => feature.stage === "removed")
    .map((feature) => feature.key)
    .sort(),
  retiredFeatureKeys,
  deprecatedFeatureKeys: featureCatalog
    .filter((feature) => feature.stage === "deprecated")
    .map((feature) => feature.key)
    .sort(),
  legacyFeatureAliases,
};

const generatedSource = `// Generated by scripts/sync-codex.mjs. Do not edit by hand.\n\nexport const CODEX_TARGET = ${JSON.stringify(target, null, 2)} as const;\n`;

await Promise.all([
  copyFile(schemaSource, join(projectRoot, "config.schema.json")),
  writeFile(join(projectRoot, "src/codex-target.generated.ts"), generatedSource, "utf8"),
]);

process.stdout.write(
  `Synced Codex ${target.sourceRevision.slice(0, 12)} with ${models.length} GPT-5.6 models.\n`,
);

function resolveSourceRoot(args) {
  const sourceIndex = args.indexOf("--source");
  if (sourceIndex >= 0) {
    const value = args[sourceIndex + 1];
    if (!value) {
      throw new Error("--source requires a path");
    }
    return resolve(expandHome(value));
  }
  const positional = args.find((arg) => !arg.startsWith("-"));
  if (!positional) {
    throw new Error("Pass the Codex checkout with `--source /path/to/codex`.");
  }
  return resolve(expandHome(positional));
}

function expandHome(path) {
  if (path === "~") {
    return homedir();
  }
  if (path.startsWith("~/")) {
    return join(homedir(), path.slice(2));
  }
  return path;
}

function supportsPersonality(modelMessages) {
  const template = modelMessages?.instructions_template;
  const variables = modelMessages?.instructions_variables;
  return Boolean(
    template?.includes("{{ personality }}") &&
      variables &&
      variables.personality_default != null &&
      variables.personality_friendly != null &&
      variables.personality_pragmatic != null,
  );
}

function parseFeatureCatalog(source) {
  return source
    .split("FeatureSpec {")
    .slice(1)
    .map((chunk) => chunk.split("\n    },", 1)[0])
    .flatMap((block) => {
      const id = block.match(/\bid:\s*Feature::(\w+)/)?.[1];
      const key = block.match(/\bkey:\s*"([^"]+)"/)?.[1];
      const stage = block.match(/\bstage:\s*Stage::(UnderDevelopment|Experimental|Stable|Deprecated|Removed)\b/)?.[1];
      if (!id || !key || !stage) {
        return [];
      }
      return [{ id, key, stage: stage.toLowerCase() }];
    });
}

function parseFeatureKeys(source) {
  return [...new Set([...source.matchAll(/^\s*key:\s*"([^"]+)"/gm)].map((match) => match[1]))];
}

function parseLegacyFeatureAliases(source, featureCatalog) {
  const canonicalKeyById = new Map(featureCatalog.map((feature) => [feature.id, feature.key]));
  const entries = source
    .split("Alias {")
    .slice(1)
    .map((chunk) => chunk.split("\n    },", 1)[0])
    .filter((block) => /\blegacy_key:\s*"/.test(block))
    .map((block) => ({
      alias: block.match(/\blegacy_key:\s*"([^"]+)"/)?.[1],
      featureId: block.match(/\bfeature:\s*Feature::(\w+)/)?.[1],
    }))
    .map(({ alias, featureId }) => ({
      alias,
      canonical: featureId ? canonicalKeyById.get(featureId) : undefined,
    }));
  const unresolved = entries.filter((entry) => !entry.alias || !entry.canonical);
  if (unresolved.length > 0) {
    throw new Error(`Could not resolve all legacy feature aliases in ${legacyFeaturesSource}`);
  }
  return Object.fromEntries(
    entries
      .map((entry) => [entry.alias, entry.canonical])
      .sort(([left], [right]) => left.localeCompare(right)),
  );
}

function parseHistoricalFeatureKeys(source) {
  return [
    ...new Set(
      [...source.matchAll(/^[+-]\s*key:\s*"([^"]+)"/gm)].map((match) => match[1]),
    ),
  ].sort();
}

function gitOutput(cwd, args) {
  return execFileSync("git", args, {
    cwd,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  }).trim();
}

function maxVersion(versions) {
  return [...versions].sort((left, right) => {
    const leftParts = left.split(".").map(Number);
    const rightParts = right.split(".").map(Number);
    for (let index = 0; index < Math.max(leftParts.length, rightParts.length); index += 1) {
      const difference = (leftParts[index] ?? 0) - (rightParts[index] ?? 0);
      if (difference !== 0) {
        return difference;
      }
    }
    return 0;
  }).at(-1);
}
