// Generated by scripts/sync-codex.mjs. Do not edit by hand.

export const CODEX_TARGET = {
  "sourceRevision": "78ad6e6bfd1d3b6a209acd3ef82172a96b25179c",
  "sourceCommitDate": "2026-07-12T22:21:53-07:00",
  "minimumClientVersion": "0.144.0",
  "defaultModel": "gpt-5.6-sol",
  "models": [
    {
      "id": "gpt-5.6-sol",
      "displayName": "GPT-5.6-Sol",
      "contextWindow": 372000,
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
        "ultra"
      ],
      "defaultReasoningEffort": "low",
      "defaultReasoningSummary": "none",
      "supportsVerbosity": true,
      "serviceTiers": [
        "priority"
      ],
      "minimumClientVersion": "0.144.0",
      "toolMode": "code_mode_only",
      "multiAgentVersion": "v2",
      "supportsPersonality": false
    },
    {
      "id": "gpt-5.6-terra",
      "displayName": "GPT-5.6-Terra",
      "contextWindow": 372000,
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
        "ultra"
      ],
      "defaultReasoningEffort": "medium",
      "defaultReasoningSummary": "none",
      "supportsVerbosity": true,
      "serviceTiers": [
        "priority"
      ],
      "minimumClientVersion": "0.144.0",
      "toolMode": "code_mode_only",
      "multiAgentVersion": "v2",
      "supportsPersonality": false
    },
    {
      "id": "gpt-5.6-luna",
      "displayName": "GPT-5.6-Luna",
      "contextWindow": 372000,
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "defaultReasoningEffort": "medium",
      "defaultReasoningSummary": "none",
      "supportsVerbosity": true,
      "serviceTiers": [
        "priority"
      ],
      "minimumClientVersion": "0.144.0",
      "toolMode": "code_mode_only",
      "multiAgentVersion": "v1",
      "supportsPersonality": false
    }
  ],
  "removedFeatureKeys": [
    "apply_patch_freeform",
    "apps_mcp_path_override",
    "codex_git_commit",
    "collaboration_modes",
    "elevated_windows_sandbox",
    "experimental_windows_sandbox",
    "external_migration",
    "image_detail_original",
    "js_repl",
    "js_repl_tools_only",
    "multi_agent_mode",
    "plugin_hooks",
    "remote_control",
    "remote_models",
    "request_rule",
    "resize_all_images",
    "responses_websockets",
    "responses_websockets_v2",
    "search_tool",
    "skill_env_var_dependency_prompt",
    "sqlite",
    "steer",
    "terminal_resize_reflow",
    "tool_search",
    "tool_search_always_defer_mcp_tools",
    "tui_app_server",
    "unavailable_dummy_tools",
    "undo",
    "use_linux_sandbox_bwrap",
    "workspace_owner_usage_nudge"
  ],
  "retiredFeatureKeys": [
    "approve_all",
    "apps_mcp_gateway",
    "auto_compaction",
    "builtin_mcp",
    "child_agents_md",
    "debug_hide_spawn_agent_metadata",
    "enable_elevated_windows_sandbox",
    "exec_policy",
    "experimental_sandbox_command_assessment",
    "general_analytics",
    "ghost_commit",
    "hierarchical_agents",
    "parallel",
    "plan_tool",
    "powershell_utf8",
    "realtime_conversation_v2",
    "remote_compaction",
    "responses_websocket_response_processed",
    "rmcp_client",
    "shell_command_tool",
    "skill_approval",
    "skills",
    "sleep_tool",
    "smart_approvals",
    "spawn_csv",
    "streamable_shell",
    "tui2",
    "view_image_tool",
    "voice_transcription",
    "warnings"
  ],
  "deprecatedFeatureKeys": [
    "use_legacy_landlock",
    "web_search_cached",
    "web_search_request"
  ],
  "legacyFeatureAliases": {
    "codex_hooks": "hooks",
    "collab": "multi_agent",
    "connectors": "apps",
    "enable_experimental_windows_sandbox": "experimental_windows_sandbox",
    "experimental_use_unified_exec_tool": "unified_exec",
    "imagegenext": "image_generation",
    "memory_tool": "memories",
    "request_permissions": "exec_permission_approvals",
    "telepathy": "chronicle",
    "web_search": "web_search_request"
  }
} as const;
